services:
- postgresql
language: ruby
rvm:
- 2.3.1
env:
- DB=postgresql
before_script:
//- psql -c 'create database klink_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec spec/
deploy:
  provider: heroku
  app: klinkapp